name: 🌱 Deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: commit to gh-pages
        run: |
          mv dist/* .
          git checkout -b gh-pages
          git add .
          git commit -m "update littlle link"
          git push -u origin gh-pages --force
